Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kivy\logger.py", line 310, in emit
  File "kivy\logger.py", line 284, in _configure
  File "logging\__init__.py", line 1468, in info
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1098, in emit
  File "logging\__init__.py", line 942, in format
  File "kivy\logger.py", line 540, in format
  File "kivy\logger.py", line 424, in __init__
  File "logging\__init__.py", line 317, in __init__
  File "ntpath.py", line 216, in basename
  File "ntpath.py", line 186, in split
  File "ntpath.py", line 35, in _get_bothseps
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\__init__.py", line 1101, in emit
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "kivy\__init__.py", line 512, in <module>
  File "logging\__init__.py", line 1468, in info
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "kivy\logger.py", line 319, in emit
  File "logging\__init__.py", line 1503, in exception
  File "logging\__init__.py", line 1497, in error
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1106, in emit
  File "logging\__init__.py", line 1019, in handleError
  File "kivy\logger.py", line 390, in write
  File "logging\__init__.py", line 1480, in warning
  File "logging\__init__.py", line 1615, in _log
  File "logging\__init__.py", line 1625, in handle
  File "logging\__init__.py", line 1687, in callHandlers
  File "logging\__init__.py", line 967, in handle
  File "logging\__init__.py", line 1098, in emit
  File "logging\__init__.py", line 942, in format
  File "kivy\logger.py", line 540, in format
  File "kivy\logger.py", line 424, in __init__
  File "logging\__init__.py", line 317, in __init__
  File "ntpath.py", line 216, in basename
  File "ntpath.py", line 186, in split
  File "ntpath.py", line 35, in _get_bothseps
RecursionError: maximum recursion depth exceeded while calling a Python object
